---
- name: Clone dotfiles
  git:
    repo: https://github.com/pe-ter-/dotfiles.git
    dest: "{{ dotfiles_path }}"
  become: true
  become_user: "{{ vimmer_user.name }}"

- name: ~/.config/nvim exists
  file:
    path: "{{ nvim_config_path }}"
    state: directory
    owner: "{{ vimmer_user.name }}"
    group: "{{ vimmer_user.group }}"

- name: Symlinks of dotfiles created
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: "{{ vimmer_user.name }}"
    group: "{{ vimmer_user.group }}"
  with_items:
    "{{ symlink_items }}"
