---
- name: Clone dotfiles
  git:
    repo: https://github.com/pe-ter-/dotfiles.git
    dest: "{{ dotfiles_path }}"
  become: true
  become_user: "{{ vimmer_user.name }}"

- name: configuration directories exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ vimmer_user.name }}"
    group: "{{ vimmer_user.group }}"
  with_items:
    "{{ config_paths }}"

- name: Symlinks of dotfiles created
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
    owner: "{{ vimmer_user.name }}"
    group: "{{ vimmer_user.group }}"
  with_items:
    "{{ symlink_items }}"
