---
- name: Install prerequisites for neovim
  apt:
    name: "{{ item }}"
  with_items:
    - software-properties-common

- name: Add apt-repository ppa:neovim-ppa/unstable
  apt_repository:
    repo: "ppa:neovim-ppa/unstable"

- name: Update apt cache
  apt:
    update_cache: true

- name: Install neovim
  apt:
    name: neovim
