---
- name: Check peco is exists
  stat:
    path: "{{ home_dir }}/bin/peco"
  register: p

- block:
  - name: ~/bin exists
    file:
      path: "{{ home_dir }}/bin"
      state: directory
      owner: "{{ vimmer_user.name }}"
      group: "{{ vimmer_user.group }}"

  - name: download peco binary
    get_url:
      url: "https://github.com/peco/peco/releases/download/{{ peco_version }}/peco_linux_amd64.tar.gz"
      dest: "{{ home_dir }}/bin/peco_linux_amd64.tar.gz"
      owner: "{{ vimmer_user.name }}"
      group: "{{ vimmer_user.group }}"

  - name: peco installed
    command: "{{ item }}"
    args:
      chdir: "{{ home_dir }}/bin"
    with_items:
      - tar xzf peco_linux_amd64.tar.gz
      - mv peco_linux_amd64/peco ./
    become: true
    become_user: "{{ vimmer_user.name }}"

  - name: cleanup peco installer
    file:
      path: "{{ item }}"
      state: absent
    with_items:
      - "{{ home_dir }}/bin/peco_linux_amd64.tar.gz"
      - "{{ home_dir }}/bin/peco_linux_amd64/"
  when: not p.stat.exists
