---
- name: Install requirements for building python
  apt:
    name: "{{ item }}"
    update_cache: true
  with_items:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - libncursesw5-dev
    - xz-utils
    - tk-dev

- name: Install pyenv
  git:
    repo: https://github.com/yyuu/pyenv.git
    dest: "{{ home_dir }}/.pyenv"
  become: true
  become_user: "{{ vimmer_user.name }}"

- name: Install python
  shell: |-
    if [ ! -d "{{ home_dir }}/.pyenv/versions/{{ item }}" ]; then
      {{ zsh_path.stdout }} -lc "pyenv install {{ item }}"
    fi
  become: true
  become_user: "{{ vimmer_user.name }}"
  with_items:
    "{{ pyenv_versions }}"

- name: Set pyenv global as "{{ pyenv_versions }}"
  command: '{{ zsh_path.stdout }} -lc "pyenv global {{ pyenv_versions | join(" ") }}"'
  become: true
  become_user: "{{ vimmer_user.name }}"

- name: Install neovim plugin
  command: "{{ home_dir }}/.pyenv/versions/{{ item }}/bin/pip install neovim"
  become: true
  become_user: "{{ vimmer_user.name }}"
  with_items:
    "{{ pyenv_versions }}"
